/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum AccountResultAllOfTypeEnum {

    TRIAL = 'trial',
    FULL = 'full'
}
export enum AccountResultAllOfStatusEnum {

    ACTIVE = 'active',
    SUSPENDED = 'suspended',
    CLOSED = 'closed'
}
export class AccountResultAllOf {
    /**
    * String that uniquely identifies this account resource.
    */
    'accountId'?: string;
    /**
    * The API key assigned to this account. This key must be kept a secret by the customer.
    */
    'apiKey'?: string;
    /**
    * A description for this account.
    */
    'alias'?: string;
    /**
    * A string that identifies a category or group to which the account belongs.
    */
    'label'?: string;
    /**
    * The type of this account. It is one of: trial or full.
    */
    'type'?: AccountResultAllOfTypeEnum;
    /**
    * The status of this account. It is one of: active, suspended, or closed.
    */
    'status'?: AccountResultAllOfStatusEnum;
    /**
    * The list of subresources for this account.
    */
    'subresourceUris'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string, defaultValue: any}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AccountResultAllOfTypeEnum",
            "format": "",
            
            
            "defaultValue": undefined

        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountResultAllOfStatusEnum",
            "format": "",
            
            
            "defaultValue": undefined

        },
        {
            "name": "subresourceUris",
            "baseName": "subresourceUris",
            "type": "any",
            "format": "",
            
            
            "defaultValue": undefined
        }    ];

    static getAttributeTypeMap() {
        return AccountResultAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

