/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountResultAllOf } from './AccountResultAllOf';
import { MutableResourceModel } from './MutableResourceModel';
import { HttpFile } from '../http/http';

export class AccountResult {
    /**
    * The URI for this resource, relative to /apiserver.
    */
    'uri'?: string;
    /**
    * The date that this resource was created (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).
    */
    'dateCreated'?: string;
    /**
    * The date that this resource was last updated (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).
    */
    'dateUpdated'?: string;
    /**
    * Revision count for the resource. This count is set to 1 on creation and is incremented every time it is updated.
    */
    'revision'?: number;
    /**
    * String that uniquely identifies this account resource.
    */
    'accountId'?: string;
    /**
    * The API key assigned to this account. This key must be kept a secret by the customer.
    */
    'apiKey'?: string;
    /**
    * A description for this account.
    */
    'alias'?: string;
    /**
    * A string that identifies a category or group to which the account belongs.
    */
    'label'?: string;
    /**
    * The type of this account. It is one of: trial or full.
    */
    'type'?: AccountResultTypeEnum;
    /**
    * The status of this account. It is one of: active, suspended, or closed.
    */
    'status'?: AccountResultStatusEnum;
    /**
    * The list of subresources for this account.
    */
    'subresourceUris'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "string",
            "format": ""
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "number",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AccountResultTypeEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountResultStatusEnum",
            "format": ""
        },
        {
            "name": "subresourceUris",
            "baseName": "subresourceUris",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountResult.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AccountResultTypeEnum = "trial" | "full" ;
export type AccountResultStatusEnum = "active" | "suspended" | "closed" ;

