/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerclCommand } from "./../models/PerclCommand";
import { HttpFile } from "../http/http";

/**
 * The `AddToConference` command adds a Participant to a Conference. Two Call legs can be bridged together by creating a Conference and adding both Call legs to it via `AddToConference`.
 */

interface AttributeType {
  name: string;
  baseName: string;
  type: string;
  format: string;
  defaultValue: any;
}
interface ArgumentsType {
  /**
    * CodegenProperty{openApiType='boolean', baseName='allowCallControl', complexType='null', getter='getAllowCallControl', setter='setAllowCallControl', description='If `true`, Call control will be enabled for this Participant\'s Call leg.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='allowCallControl', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.allowCallControl;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='If `true`, Call control will be enabled for this Participant's Call leg.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "If `true`, Call control will be enabled for this Participant's Call leg.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='allowCallControl', nameInPascalCase='AllowCallControl', nameInSnakeCase='ALLOW_CALL_CONTROL', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  allowCallControl?: boolean;
  /**
    * CodegenProperty{openApiType='string', baseName='callControlSequence', complexType='null', getter='getCallControlSequence', setter='setCallControlSequence', description='Defines a sequence of digits that, when entered by this caller, invokes the `callControlUrl`. Only digits plus \'*\', and \'#\' may be used.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='callControlSequence', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.callControlSequence;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Defines a sequence of digits that, when entered by this caller, invokes the `callControlUrl`. Only digits plus '*', and '#' may be used.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "Defines a sequence of digits that, when entered by this caller, invokes the `callControlUrl`. Only digits plus '*', and '#' may be used.",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='callControlSequence', nameInPascalCase='CallControlSequence', nameInSnakeCase='CALL_CONTROL_SEQUENCE', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  callControlSequence?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='callControlUrl', complexType='null', getter='getCallControlUrl', setter='setCallControlUrl', description='URL to be invoked when this Participant enters the digit sequence defined in the `callControlSequence` attribute.', dataType='string', datatypeWithEnum='string', dataFormat='uri', name='callControlUrl', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.callControlUrl;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='URL to be invoked when this Participant enters the digit sequence defined in the `callControlSequence` attribute.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "URL to be invoked when this Participant enters the digit sequence defined in the `callControlSequence` attribute.",
  "format" : "uri",
  "type" : "string",
  "x-is-uri" : true,
  "x-is-url" : true
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=true, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={x-is-url=true, x-is-uri=true}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='callControlUrl', nameInPascalCase='CallControlUrl', nameInSnakeCase='CALL_CONTROL_URL', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=uri, dependentRequired=null, contains=null}
     */
  callControlUrl?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='conferenceId', complexType='null', getter='getConferenceId', setter='setConferenceId', description='ID of the Conference to which to add the Participant (Call leg). Conference must exist or an error will result.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='conferenceId', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.conferenceId;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='ID of the Conference to which to add the Participant (Call leg). Conference must exist or an error will result.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "ID of the Conference to which to add the Participant (Call leg). Conference must exist or an error will result.",
  "type" : "string",
  "x-is-required" : true
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=true, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={x-is-required=true}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='conferenceId', nameInPascalCase='ConferenceId', nameInSnakeCase='CONFERENCE_ID', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  conferenceId: string;
  /**
    * CodegenProperty{openApiType='string', baseName='leaveConferenceUrl', complexType='null', getter='getLeaveConferenceUrl', setter='setLeaveConferenceUrl', description='URL to be invoked when the Participant leaves the Conference. ', dataType='string', datatypeWithEnum='string', dataFormat='uri', name='leaveConferenceUrl', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.leaveConferenceUrl;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='URL to be invoked when the Participant leaves the Conference. ', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "URL to be invoked when the Participant leaves the Conference. ",
  "format" : "uri",
  "type" : "string",
  "x-is-uri" : true,
  "x-is-url" : true
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=true, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={x-is-url=true, x-is-uri=true}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='leaveConferenceUrl', nameInPascalCase='LeaveConferenceUrl', nameInSnakeCase='LEAVE_CONFERENCE_URL', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=uri, dependentRequired=null, contains=null}
     */
  leaveConferenceUrl?: string;
  /**
    * CodegenProperty{openApiType='boolean', baseName='listen', complexType='null', getter='getListen', setter='setListen', description='If `true`, the Participant joins the Conference with listen privileges. This may be modified later via the REST API or `SetListen` PerCL command.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='listen', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.listen;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='If `true`, the Participant joins the Conference with listen privileges. This may be modified later via the REST API or `SetListen` PerCL command.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "If `true`, the Participant joins the Conference with listen privileges. This may be modified later via the REST API or `SetListen` PerCL command.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='listen', nameInPascalCase='Listen', nameInSnakeCase='LISTEN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  listen?: boolean;
  /**
    * CodegenProperty{openApiType='string', baseName='notificationUrl', complexType='null', getter='getNotificationUrl', setter='setNotificationUrl', description='When the Participant enters the Conference, this URL will be invoked using an HTTP POST request with the standard request parameters.', dataType='string', datatypeWithEnum='string', dataFormat='uri', name='notificationUrl', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.notificationUrl;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='When the Participant enters the Conference, this URL will be invoked using an HTTP POST request with the standard request parameters.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "When the Participant enters the Conference, this URL will be invoked using an HTTP POST request with the standard request parameters.",
  "format" : "uri",
  "type" : "string",
  "x-is-uri" : true,
  "x-is-url" : true
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=true, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={x-is-url=true, x-is-uri=true}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='notificationUrl', nameInPascalCase='NotificationUrl', nameInSnakeCase='NOTIFICATION_URL', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=uri, dependentRequired=null, contains=null}
     */
  notificationUrl?: string;
  /**
    * CodegenProperty{openApiType='boolean', baseName='startConfOnEnter', complexType='null', getter='getStartConfOnEnter', setter='setStartConfOnEnter', description='Flag that indicates whether a Conference starts upon entry of this particular Participant. This is usually set to `true` for moderators and `false` for all other Participants.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='startConfOnEnter', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.startConfOnEnter;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Flag that indicates whether a Conference starts upon entry of this particular Participant. This is usually set to `true` for moderators and `false` for all other Participants.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "Flag that indicates whether a Conference starts upon entry of this particular Participant. This is usually set to `true` for moderators and `false` for all other Participants.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='startConfOnEnter', nameInPascalCase='StartConfOnEnter', nameInSnakeCase='START_CONF_ON_ENTER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  startConfOnEnter?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='talk', complexType='null', getter='getTalk', setter='setTalk', description='If `true`, the Participant joins the Conference with talk privileges. This may be modified later via the REST API or `SetTalk` PerCL command. ', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='talk', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.talk;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='If `true`, the Participant joins the Conference with talk privileges. This may be modified later via the REST API or `SetTalk` PerCL command. ', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "If `true`, the Participant joins the Conference with talk privileges. This may be modified later via the REST API or `SetTalk` PerCL command. ",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='talk', nameInPascalCase='Talk', nameInSnakeCase='TALK', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  talk?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='dtmfPassThrough', complexType='null', getter='getDtmfPassThrough', setter='setDtmfPassThrough', description='If `true`, the Participant joins the Conference with dtmfPassThrough privileges. This may be modified later via the REST API or `SetDTMFPassThrough` PerCL command. ', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='dtmfPassThrough', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.dtmfPassThrough;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='If `true`, the Participant joins the Conference with dtmfPassThrough privileges. This may be modified later via the REST API or `SetDTMFPassThrough` PerCL command. ', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "If `true`, the Participant joins the Conference with dtmfPassThrough privileges. This may be modified later via the REST API or `SetDTMFPassThrough` PerCL command. ",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='dtmfPassThrough', nameInPascalCase='DtmfPassThrough', nameInSnakeCase='DTMF_PASS_THROUGH', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  dtmfPassThrough?: boolean;
}
export class AddToConference extends PerclCommand {
  /**
   * If `true`, Call control will be enabled for this Participant\'s Call leg.
   */
  "allowCallControl"?: boolean;
  /**
   * Defines a sequence of digits that, when entered by this caller, invokes the `callControlUrl`. Only digits plus \'*\', and \'#\' may be used.
   */
  "callControlSequence"?: string;
  /**
   * URL to be invoked when this Participant enters the digit sequence defined in the `callControlSequence` attribute.
   */
  "callControlUrl"?: string;
  /**
   * ID of the Conference to which to add the Participant (Call leg). Conference must exist or an error will result.
   */
  "conferenceId": string;
  /**
   * URL to be invoked when the Participant leaves the Conference.
   */
  "leaveConferenceUrl"?: string;
  /**
   * If `true`, the Participant joins the Conference with listen privileges. This may be modified later via the REST API or `SetListen` PerCL command.
   */
  "listen"?: boolean;
  /**
   * When the Participant enters the Conference, this URL will be invoked using an HTTP POST request with the standard request parameters.
   */
  "notificationUrl"?: string;
  /**
   * Flag that indicates whether a Conference starts upon entry of this particular Participant. This is usually set to `true` for moderators and `false` for all other Participants.
   */
  "startConfOnEnter"?: boolean;
  /**
   * If `true`, the Participant joins the Conference with talk privileges. This may be modified later via the REST API or `SetTalk` PerCL command.
   */
  "talk"?: boolean;
  /**
   * If `true`, the Participant joins the Conference with dtmfPassThrough privileges. This may be modified later via the REST API or `SetDTMFPassThrough` PerCL command.
   */
  "dtmfPassThrough"?: boolean;

  static readonly discriminator: string | undefined = "command";

  static readonly attributeTypeMap: AttributeType[] = [
    {
      name: "allowCallControl",
      baseName: "allowCallControl",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "callControlSequence",
      baseName: "callControlSequence",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "callControlUrl",
      baseName: "callControlUrl",
      type: "string",
      format: "uri",

      defaultValue: undefined,
    },
    {
      name: "conferenceId",
      baseName: "conferenceId",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "leaveConferenceUrl",
      baseName: "leaveConferenceUrl",
      type: "string",
      format: "uri",

      defaultValue: undefined,
    },
    {
      name: "listen",
      baseName: "listen",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "notificationUrl",
      baseName: "notificationUrl",
      type: "string",
      format: "uri",

      defaultValue: undefined,
    },
    {
      name: "startConfOnEnter",
      baseName: "startConfOnEnter",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "talk",
      baseName: "talk",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "dtmfPassThrough",
      baseName: "dtmfPassThrough",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
  ];

  static getAttributeTypeMap(): AttributeType[] {
    return super.getAttributeTypeMap().concat(AddToConference.attributeTypeMap);
  }
  public constructor(args: ArgumentsType) {
    super({ command: "AddToConference" });
    const assign = <T>(attribute: keyof ArgumentsType): T => {
      return (
        args.hasOwnProperty(attribute)
          ? args[attribute]
          : AddToConference.attributeTypeMap.find(
              (attr) => attr.name === attribute,
            )?.defaultValue
      ) as T;
    };
    this["allowCallControl"] = assign<boolean>("allowCallControl");
    this["callControlSequence"] = assign<string>("callControlSequence");
    this["callControlUrl"] = assign<string>("callControlUrl");
    this["conferenceId"] = assign<string>("conferenceId");
    this["leaveConferenceUrl"] = assign<string>("leaveConferenceUrl");
    this["listen"] = assign<boolean>("listen");
    this["notificationUrl"] = assign<string>("notificationUrl");
    this["startConfOnEnter"] = assign<boolean>("startConfOnEnter");
    this["talk"] = assign<boolean>("talk");
    this["dtmfPassThrough"] = assign<boolean>("dtmfPassThrough");
  }
}
