/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';


interface AttributeType {
    name: string
    baseName: string
    type: string
    format: string
    defaultValue: any
}
interface ArgumentsType {
    'accountId'?: string;
    'conferenceId'?: string;
    'callId'?: string;
    'talk'?: boolean;
    'listen'?: boolean;
    'startConfOnEnter'?: boolean;
}
export class ConferenceParticipantResultAllOf {
    /**
    * ID of the account that created this participant.
    */
    'accountId'?: string;
    /**
    * ID of the conference this participant is in.
    */
    'conferenceId'?: string;
    /**
    * ID of the Call associated with this Participant.
    */
    'callId'?: string;
    /**
    * True if this Participant has talk privileges in the Conference. False otherwise.
    */
    'talk'?: boolean;
    /**
    * True if this Participant has listen privileges in the Conference. False otherwise.
    */
    'listen'?: boolean;
    /**
    * True if this Participant joining the Conference caused the Conference to start (status = inProgress). False otherwise.
    */
    'startConfOnEnter'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: AttributeType[] = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "conferenceId",
            "baseName": "conferenceId",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "callId",
            "baseName": "callId",
            "type": "string",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "talk",
            "baseName": "talk",
            "type": "boolean",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "listen",
            "baseName": "listen",
            "type": "boolean",
            "format": "",
            
            
            "defaultValue": undefined
        },
        {
            "name": "startConfOnEnter",
            "baseName": "startConfOnEnter",
            "type": "boolean",
            "format": "",
            
            
            "defaultValue": undefined
        }    ];

    static getAttributeTypeMap(): AttributeType[] {
        return ConferenceParticipantResultAllOf.attributeTypeMap;
    }

    public constructor(args: ArgumentsType) {
        const preparedArgs = ConferenceParticipantResultAllOf.attributeTypeMap.reduce((acc: Partial<ArgumentsType>, attr: AttributeType) => {
            const val = args[attr.name as keyof ArgumentsType] ?? attr.defaultValue
            if (val !== undefined) {
                acc[attr.name as keyof ArgumentsType] = val
            }
            return acc
        }, {})
        Object.assign(this, preparedArgs)
    }
}

