/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http";

interface AttributeType {
  name: string;
  baseName: string;
  type: string;
  format: string;
  defaultValue: any;
}
interface ArgumentsType {
  /**
    * CodegenProperty{openApiType='string', baseName='uri', complexType='null', getter='getUri', setter='setUri', description='The URI for this resource, relative to /apiserver.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='uri', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.uri;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='The URI for this resource, relative to /apiserver.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "The URI for this resource, relative to /apiserver.",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='uri', nameInPascalCase='Uri', nameInSnakeCase='URI', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  uri?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='dateCreated', complexType='null', getter='getDateCreated', setter='setDateCreated', description='The date that this resource was created (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).', dataType='string', datatypeWithEnum='string', dataFormat='null', name='dateCreated', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.dateCreated;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='The date that this resource was created (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "The date that this resource was created (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='dateCreated', nameInPascalCase='DateCreated', nameInSnakeCase='DATE_CREATED', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  dateCreated?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='dateUpdated', complexType='null', getter='getDateUpdated', setter='setDateUpdated', description='The date that this resource was last updated (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).', dataType='string', datatypeWithEnum='string', dataFormat='null', name='dateUpdated', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.dateUpdated;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='The date that this resource was last updated (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "The date that this resource was last updated (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='dateUpdated', nameInPascalCase='DateUpdated', nameInSnakeCase='DATE_UPDATED', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  dateUpdated?: string;
  /**
    * CodegenProperty{openApiType='integer', baseName='revision', complexType='null', getter='getRevision', setter='setRevision', description='Revision count for the resource. This count is set to 1 on creation and is incremented every time it is updated.', dataType='number', datatypeWithEnum='number', dataFormat='null', name='revision', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.revision;', baseType='number', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Revision count for the resource. This count is set to 1 on creation and is incremented every time it is updated.', maxLength=null, minLength=null, pattern='null', example='1', jsonSchema='{
  "description" : "Revision count for the resource. This count is set to 1 on creation and is incremented every time it is updated.",
  "type" : "integer"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=true, isInteger=true, isShort=false, isLong=false, isUnboundedInteger=true, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='revision', nameInPascalCase='Revision', nameInSnakeCase='REVISION', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  revision?: number;
  /**
    * CodegenProperty{openApiType='string', baseName='accountId', complexType='null', getter='getAccountId', setter='setAccountId', description='ID of the account that created this participant.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='accountId', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.accountId;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='ID of the account that created this participant.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "ID of the account that created this participant.",
  "nullable" : true,
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='accountId', nameInPascalCase='AccountId', nameInSnakeCase='ACCOUNT_ID', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  accountId?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='conferenceId', complexType='null', getter='getConferenceId', setter='setConferenceId', description='ID of the conference this participant is in.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='conferenceId', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.conferenceId;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='ID of the conference this participant is in.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "ID of the conference this participant is in.",
  "nullable" : true,
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='conferenceId', nameInPascalCase='ConferenceId', nameInSnakeCase='CONFERENCE_ID', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  conferenceId?: string;
  /**
    * CodegenProperty{openApiType='string', baseName='callId', complexType='null', getter='getCallId', setter='setCallId', description='ID of the Call associated with this Participant.', dataType='string', datatypeWithEnum='string', dataFormat='null', name='callId', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.callId;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='ID of the Call associated with this Participant.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "ID of the Call associated with this Participant.",
  "nullable" : true,
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='callId', nameInPascalCase='CallId', nameInSnakeCase='CALL_ID', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  callId?: string;
  /**
    * CodegenProperty{openApiType='boolean', baseName='talk', complexType='null', getter='getTalk', setter='setTalk', description='True if this Participant has talk privileges in the Conference. False otherwise.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='talk', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.talk;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='True if this Participant has talk privileges in the Conference. False otherwise.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "True if this Participant has talk privileges in the Conference. False otherwise.",
  "nullable" : true,
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='talk', nameInPascalCase='Talk', nameInSnakeCase='TALK', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  talk?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='listen', complexType='null', getter='getListen', setter='setListen', description='True if this Participant has listen privileges in the Conference. False otherwise.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='listen', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.listen;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='True if this Participant has listen privileges in the Conference. False otherwise.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "True if this Participant has listen privileges in the Conference. False otherwise.",
  "nullable" : true,
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='listen', nameInPascalCase='Listen', nameInSnakeCase='LISTEN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  listen?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='dtmfPassThrough', complexType='null', getter='getDtmfPassThrough', setter='setDtmfPassThrough', description='True if this Participant had dtmfPassThrough privileges in the Conference. False otherwise.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='dtmfPassThrough', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.dtmfPassThrough;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='True if this Participant had dtmfPassThrough privileges in the Conference. False otherwise.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "True if this Participant had dtmfPassThrough privileges in the Conference. False otherwise.",
  "nullable" : true,
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='dtmfPassThrough', nameInPascalCase='DtmfPassThrough', nameInSnakeCase='DTMF_PASS_THROUGH', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  dtmfPassThrough?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='startConfOnEnter', complexType='null', getter='getStartConfOnEnter', setter='setStartConfOnEnter', description='True if this Participant joining the Conference caused the Conference to start (status = inProgress). False otherwise.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='startConfOnEnter', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.startConfOnEnter;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='True if this Participant joining the Conference caused the Conference to start (status = inProgress). False otherwise.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "True if this Participant joining the Conference caused the Conference to start (status = inProgress). False otherwise.",
  "nullable" : true,
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=true, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='startConfOnEnter', nameInPascalCase='StartConfOnEnter', nameInSnakeCase='START_CONF_ON_ENTER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  startConfOnEnter?: boolean;
}
export class ConferenceParticipantResult {
  /**
   * The URI for this resource, relative to /apiserver.
   */
  "uri"?: string;
  /**
   * The date that this resource was created (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).
   */
  "dateCreated"?: string;
  /**
   * The date that this resource was last updated (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT).
   */
  "dateUpdated"?: string;
  /**
   * Revision count for the resource. This count is set to 1 on creation and is incremented every time it is updated.
   */
  "revision"?: number;
  /**
   * ID of the account that created this participant.
   */
  "accountId"?: string;
  /**
   * ID of the conference this participant is in.
   */
  "conferenceId"?: string;
  /**
   * ID of the Call associated with this Participant.
   */
  "callId"?: string;
  /**
   * True if this Participant has talk privileges in the Conference. False otherwise.
   */
  "talk"?: boolean;
  /**
   * True if this Participant has listen privileges in the Conference. False otherwise.
   */
  "listen"?: boolean;
  /**
   * True if this Participant had dtmfPassThrough privileges in the Conference. False otherwise.
   */
  "dtmfPassThrough"?: boolean;
  /**
   * True if this Participant joining the Conference caused the Conference to start (status = inProgress). False otherwise.
   */
  "startConfOnEnter"?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: AttributeType[] = [
    {
      name: "uri",
      baseName: "uri",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "dateCreated",
      baseName: "dateCreated",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "dateUpdated",
      baseName: "dateUpdated",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "revision",
      baseName: "revision",
      type: "number",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "accountId",
      baseName: "accountId",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "conferenceId",
      baseName: "conferenceId",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "callId",
      baseName: "callId",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "talk",
      baseName: "talk",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "listen",
      baseName: "listen",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "dtmfPassThrough",
      baseName: "dtmfPassThrough",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "startConfOnEnter",
      baseName: "startConfOnEnter",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
  ];

  static getAttributeTypeMap(): AttributeType[] {
    return ConferenceParticipantResult.attributeTypeMap;
  }
  public constructor(args: ArgumentsType) {
    const assign = <T>(attribute: keyof ArgumentsType): T => {
      return (
        args.hasOwnProperty(attribute)
          ? args[attribute]
          : ConferenceParticipantResult.attributeTypeMap.find(
              (attr) => attr.name === attribute,
            )?.defaultValue
      ) as T;
    };
    this["uri"] = assign<string>("uri");
    this["dateCreated"] = assign<string>("dateCreated");
    this["dateUpdated"] = assign<string>("dateUpdated");
    this["revision"] = assign<number>("revision");
    this["accountId"] = assign<string>("accountId");
    this["conferenceId"] = assign<string>("conferenceId");
    this["callId"] = assign<string>("callId");
    this["talk"] = assign<boolean>("talk");
    this["listen"] = assign<boolean>("listen");
    this["dtmfPassThrough"] = assign<boolean>("dtmfPassThrough");
    this["startConfOnEnter"] = assign<boolean>("startConfOnEnter");
  }
}
