/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LogResult {
    /**
    * Time that the log was generated. The time is represented as microseconds since the Unix Epoch.
    */
    'timestamp'?: number;
    /**
    * Level of the log. Possible values are info, warning, and error.
    */
    'level'?: LogResultLevelEnum;
    /**
    * ID of the request associated with the log. The requestId is propagated across all logs generated by FreeClimb when processing a request.
    */
    'requestId'?: string;
    /**
    * ID of the account that this log was generated under.
    */
    'accountId'?: string;
    /**
    * ID of the Call associated with the log. Can be set to null if the log was generated without regard to a specific Call.
    */
    'callId'?: string;
    /**
    * A simple string describing the event being logged.
    */
    'message'?: string;
    /**
    * JSON document containing metadata about the event. Some log messages may include request and response header content in this field.
    */
    'metadata'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "LogResultLevelEnum",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "callId",
            "baseName": "callId",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogResult.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LogResultLevelEnum = "info" | "warning" | "error" ;

