/**
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerclCommand } from "./../models/PerclCommand";
import { HttpFile } from "../http/http";

/**
 * The `RecordUtterance` command records the caller\'s voice and returns the URL of a file containing the audio recording. `RecordUtterance` is blocking and is a terminal command. As such, the `actionUrl` property is required, and control of the Call picks up using the PerCL returned in response to the `actionUrl`. Recording information is returned in the `actionUrl` request.
 */

interface AttributeType {
  name: string;
  baseName: string;
  type: string;
  format: string;
  defaultValue: any;
}
interface ArgumentsType {
  /**
    * CodegenProperty{openApiType='string', baseName='actionUrl', complexType='null', getter='getActionUrl', setter='setActionUrl', description='URL to which information on the completed recording is submitted. The PerCL received in response is then used to continue with Call processing.', dataType='string', datatypeWithEnum='string', dataFormat='uri', name='actionUrl', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.actionUrl;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='URL to which information on the completed recording is submitted. The PerCL received in response is then used to continue with Call processing.', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "URL to which information on the completed recording is submitted. The PerCL received in response is then used to continue with Call processing.",
  "format" : "uri",
  "type" : "string",
  "x-is-required" : true,
  "x-is-uri" : true,
  "x-is-url" : true
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=true, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=true, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={x-is-url=true, x-is-required=true, x-is-uri=true}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='actionUrl', nameInPascalCase='ActionUrl', nameInSnakeCase='ACTION_URL', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=uri, dependentRequired=null, contains=null}
     */
  actionUrl: string;
  /**
    * CodegenProperty{openApiType='integer', baseName='silenceTimeoutMs', complexType='null', getter='getSilenceTimeoutMs', setter='setSilenceTimeoutMs', description='Interval of silence that should elapse before ending the recording.', dataType='number', datatypeWithEnum='number', dataFormat='null', name='silenceTimeoutMs', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.silenceTimeoutMs;', baseType='number', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Interval of silence that should elapse before ending the recording.', maxLength=null, minLength=null, pattern='null', example='1', jsonSchema='{
  "description" : "Interval of silence that should elapse before ending the recording.",
  "type" : "integer"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=true, isInteger=true, isShort=false, isLong=false, isUnboundedInteger=true, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='silenceTimeoutMs', nameInPascalCase='SilenceTimeoutMs', nameInSnakeCase='SILENCE_TIMEOUT_MS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  silenceTimeoutMs?: number;
  /**
    * CodegenProperty{openApiType='string', baseName='finishOnKey', complexType='null', getter='getFinishOnKey', setter='setFinishOnKey', description='Key that triggers the end of the recording. any digit, \'#\', or \'*\'', dataType='string', datatypeWithEnum='string', dataFormat='null', name='finishOnKey', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.finishOnKey;', baseType='string', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Key that triggers the end of the recording. any digit, '#', or '*'', maxLength=null, minLength=null, pattern='null', example='"string_example"', jsonSchema='{
  "description" : "Key that triggers the end of the recording. any digit, '#', or '*'",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='finishOnKey', nameInPascalCase='FinishOnKey', nameInSnakeCase='FINISH_ON_KEY', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  finishOnKey?: string;
  /**
    * CodegenProperty{openApiType='integer', baseName='maxLengthSec', complexType='null', getter='getMaxLengthSec', setter='setMaxLengthSec', description='Maximum length for the command execution in seconds.', dataType='number', datatypeWithEnum='number', dataFormat='null', name='maxLengthSec', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.maxLengthSec;', baseType='number', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Maximum length for the command execution in seconds.', maxLength=null, minLength=null, pattern='null', example='1', jsonSchema='{
  "description" : "Maximum length for the command execution in seconds.",
  "type" : "integer"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=true, isInteger=true, isShort=false, isLong=false, isUnboundedInteger=true, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='maxLengthSec', nameInPascalCase='MaxLengthSec', nameInSnakeCase='MAX_LENGTH_SEC', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  maxLengthSec?: number;
  /**
    * CodegenProperty{openApiType='boolean', baseName='playBeep', complexType='null', getter='getPlayBeep', setter='setPlayBeep', description='Indicates whether to play a beep sound before the start of the recording. If set to `false`, no beep is played.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='playBeep', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.playBeep;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Indicates whether to play a beep sound before the start of the recording. If set to `false`, no beep is played.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "Indicates whether to play a beep sound before the start of the recording. If set to `false`, no beep is played.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='playBeep', nameInPascalCase='PlayBeep', nameInSnakeCase='PLAY_BEEP', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  playBeep?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='autoStart', complexType='null', getter='getAutoStart', setter='setAutoStart', description='If `false`, recording begins immediately after the RecordUtterance command is processed. If `true`, recording begins when audio is present and if audio begins before the `maxLengthSec` timeout. If no audio begins before `maxLengthSec`, no recording is generated.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='autoStart', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.autoStart;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='If `false`, recording begins immediately after the RecordUtterance command is processed. If `true`, recording begins when audio is present and if audio begins before the `maxLengthSec` timeout. If no audio begins before `maxLengthSec`, no recording is generated.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "If `false`, recording begins immediately after the RecordUtterance command is processed. If `true`, recording begins when audio is present and if audio begins before the `maxLengthSec` timeout. If no audio begins before `maxLengthSec`, no recording is generated.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='autoStart', nameInPascalCase='AutoStart', nameInSnakeCase='AUTO_START', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  autoStart?: boolean;
  /**
    * CodegenProperty{openApiType='boolean', baseName='privacyMode', complexType='null', getter='getPrivacyMode', setter='setPrivacyMode', description='Parameter `privacyMode` will not log the `text` as required by PCI compliance.', dataType='boolean', datatypeWithEnum='boolean', dataFormat='null', name='privacyMode', min='null', max='null', defaultValue='undefined', defaultValueWithParam=' = data.privacyMode;', baseType='boolean', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Parameter `privacyMode` will not log the `text` as required by PCI compliance.', maxLength=null, minLength=null, pattern='null', example='true', jsonSchema='{
  "description" : "Parameter `privacyMode` will not log the `text` as required by PCI compliance.",
  "type" : "boolean"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=true, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='privacyMode', nameInPascalCase='PrivacyMode', nameInSnakeCase='PRIVACY_MODE', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
     */
  privacyMode?: boolean;
}
export class RecordUtterance extends PerclCommand {
  /**
   * URL to which information on the completed recording is submitted. The PerCL received in response is then used to continue with Call processing.
   */
  "actionUrl": string;
  /**
   * Interval of silence that should elapse before ending the recording.
   */
  "silenceTimeoutMs"?: number;
  /**
   * Key that triggers the end of the recording. any digit, \'#\', or \'*\'
   */
  "finishOnKey"?: string;
  /**
   * Maximum length for the command execution in seconds.
   */
  "maxLengthSec"?: number;
  /**
   * Indicates whether to play a beep sound before the start of the recording. If set to `false`, no beep is played.
   */
  "playBeep"?: boolean;
  /**
   * If `false`, recording begins immediately after the RecordUtterance command is processed. If `true`, recording begins when audio is present and if audio begins before the `maxLengthSec` timeout. If no audio begins before `maxLengthSec`, no recording is generated.
   */
  "autoStart"?: boolean;
  /**
   * Parameter `privacyMode` will not log the `text` as required by PCI compliance.
   */
  "privacyMode"?: boolean;

  static readonly discriminator: string | undefined = "command";

  static readonly attributeTypeMap: AttributeType[] = [
    {
      name: "actionUrl",
      baseName: "actionUrl",
      type: "string",
      format: "uri",

      defaultValue: undefined,
    },
    {
      name: "silenceTimeoutMs",
      baseName: "silenceTimeoutMs",
      type: "number",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "finishOnKey",
      baseName: "finishOnKey",
      type: "string",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "maxLengthSec",
      baseName: "maxLengthSec",
      type: "number",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "playBeep",
      baseName: "playBeep",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "autoStart",
      baseName: "autoStart",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
    {
      name: "privacyMode",
      baseName: "privacyMode",
      type: "boolean",
      format: "",

      defaultValue: undefined,
    },
  ];

  static getAttributeTypeMap(): AttributeType[] {
    return super.getAttributeTypeMap().concat(RecordUtterance.attributeTypeMap);
  }
  public constructor(args: ArgumentsType) {
    super({ command: "RecordUtterance" });
    const assign = <T>(attribute: keyof ArgumentsType): T => {
      return (
        args.hasOwnProperty(attribute)
          ? args[attribute]
          : RecordUtterance.attributeTypeMap.find(
              (attr) => attr.name === attribute,
            )?.defaultValue
      ) as T;
    };
    this["actionUrl"] = assign<string>("actionUrl");
    this["silenceTimeoutMs"] = assign<number>("silenceTimeoutMs");
    this["finishOnKey"] = assign<string>("finishOnKey");
    this["maxLengthSec"] = assign<number>("maxLengthSec");
    this["playBeep"] = assign<boolean>("playBeep");
    this["autoStart"] = assign<boolean>("autoStart");
    this["privacyMode"] = assign<boolean>("privacyMode");
  }
}
